---
title: "Sensitivity_Feed_Price"
author: "Anna Calle"
date: "4/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Load packages
library(tidyverse)
library(rnaturalearth)
library(raster)
library(ggplot2)

```

Read in Rasters
```{r}
# Read in the Empty Raster
empty_rast_econ <- raster("empty_raster.tif")

# Read in EEZ Raster
eez_econ <- raster("eez_all_1.tif")

# Read in Distance to Shore Raster
dist_shore_econ <- raster("dist_shore.tif")
plot(dist_shore_econ)

```



Setting Number of Farms per Cell
```{r}
num_farms <- 1 # number of farms per 9.2x9.2 km cell, most conservative estimate of 16 cages per/farm (per cell)
```

Calculate Fuel Costs
```{r}

############# 2/2: We're going to change the harvestable fish weight to 5kg!

# Determine Fuel Costs and Usage
fuel_consumption <- 26.96 #L/hour
vessel_speed <- 15000 #average speed in m/hr
diesel_price <- 0.92 #USD/L using 2020 exchange rate 1 usd = 4 reais
distance_to_port <- 25 #depend on cell
num_of_boats <- 2
trips_per_week <- 4 # average roundtrips per year (1 boat @ 3 trips/week, 1 @ 5 trips per week)

trips_annual <- num_of_boats * trips_per_week * 52 # roundtrips per farm per year (52 weeks a year)
one_way_trips_annual <- 2*trips_annual # (we have to double the roundtrips because we need to take into account that distance traveled happens TWICE for every round trip)

# Create raster for all fuel costs:
annual_fuel_cost_econ <- (dist_shore_econ/vessel_speed)*fuel_consumption*diesel_price*one_way_trips_annual
plot(annual_fuel_cost_econ)


# Export Fuel Cost Raster by Distance to Shore
```

Calculate Wage Costs
```{r}

# Determine Total Wage Costs
cage_size <- 6400 #m^3
farm_size <- 16 #cages
farm_volume <- 102400 #m^3

full_time_workers <- 40
monthly_hours <- 160 #hours/month per fulltime employee
annual_hours <- (monthly_hours*12)
num_of_employees <-  ##/farm
hourly_wage <- 4.50 #USD/hour average
work_days_per_month <- 20
workers_offshore <- 35
workers_onshore <- 5

# Determine Annual Fixed Wage Cost per Farm
fixed_labor_cost <- full_time_workers*hourly_wage*annual_hours

# Determine # of Annual Transit Hours
annual_transit_hours <- (dist_shore_econ/vessel_speed)*one_way_trips_annual

# Determine Annual Wage Cost for Transit Hours Per Farm
transit_cost <- workers_offshore*annual_transit_hours*hourly_wage

# Create raster for total annual wage costs
total_annual_wage_costs <- transit_cost+fixed_labor_cost

plot(total_annual_wage_costs)

```


Calculate Capital Costs
```{r}

##### Discount rate comes into play directly for the NPV equation, later.
##### Annuity gets applied now, to certain capital costs, for first profit calculation.


# Farm Design
cage_number_per_farm <- 16
cage_cost <- 312000
total_cage_cost <- cage_cost*cage_number_per_farm
weight_at_harvest <- 5 #user inputs (value is 5kg)
final_stocking_density <- 10 #user inputs (value is 10fish/m^3)
initial_stocking_density <- 3 #user inputs 3fish/m^3)
feed_conversion_ratio <- 3 #user inputs
survival_rate <- .85 #note that this is species-specific
fingerling_price <- 1.50 #USD ****
# feed_price <- 2.10 #USD/kg **** # is going to be changed
optimal_feed <- 2350080 #kg per farm/grow out cycle total amount of feed
time <- 12 #months, rotation period
# feed_annual <- (optimal_feed*feed_price) not used anywhere else (Probably should delete!!)
 
# One-time costs
farm_installation <- 139555 # (Bezerra)
farm_lease <- 8668.74 # one-time lease (Bezerra)
signaling_system <- 28021.40 # one-time system installation (Bezerra)
project_development <- 53403.69 #project development (Bezerra)
miscellaneous <- 123685.54 # one time (Bezerra)
boats <- 420376.85 #for 3 boats, one time, 1 * 16m, 2* 7m (Bezerra)


# Annual fixed costs
electric_power <- 3661.32 # (Bezerra)
mooring_maintenance <- 53191.29 # (Bezerra)
diving_maintenance <- 8427.13 # (Bezerra)
office_rent <- 36626.43 # (Bezerra)
environmental_monitoring <- 45781.04 # (Bezerra)
boat_maintenance <- 30000 # for two boats (Costello)
dockage <- 20000 # for two boats (Costello)
insurance <- 50000 # (Costello)
juv_cost_annual <- (initial_stocking_density*farm_volume*fingerling_price) # yearly cost
 
# Read in Biomass Raster
biomass_rast <- raster("cobia_biomass.tif")

# Function starts

fun_feed_price <- function(feed_price_value) {
# Create Feed Raster
feed_annual_rast <- biomass_rast*1000*feed_conversion_ratio*feed_price_value # multiplied by 1000 to convert biomass from MT to kg

# Non-Amortized Annual Fixed Costs
total_annual_fixed_costs <- (electric_power + mooring_maintenance + diving_maintenance + office_rent + environmental_monitoring + boat_maintenance + dockage + insurance + feed_annual_rast + juv_cost_annual)


# Amortized One-time Costs
one_time_fixed_costs_depreciated <- (signaling_system + miscellaneous + boats + total_cage_cost + farm_installation + farm_lease + project_development) #### ONLY PART TO AMORTIZE


# Calculate Annuity Function
# Define the discount rate
risk_rho <- 1.17647 # Discount rate = 15%
risk_discount <- (1-(1/risk_rho))
risk_discount

# Annuity Function
annuity <- function(c, r = risk_discount, t = 10) {
  a <- c/ ((1-(1+r)^-t)/r)
  return(a)
}
  
amortized_costs <- annuity(one_time_fixed_costs_depreciated)

 # Calculating TOTAL COSTS
#Adding all costs to create final cost raster
cost_total <- amortized_costs + total_annual_fixed_costs + annual_fuel_cost_econ + total_annual_wage_costs


# Create Costs of Suitable Raster
# Test
suitable_raster <- raster("cobia_suit.tif")


cost_of_suitable <- mask(cost_total, suitable_raster)

# Create Revenue Raster

price_fish <- 8.6

revenue_rast <- biomass_rast*price_fish


# Create Profit Raster
profit_raster <- revenue_rast-cost_of_suitable


# Create NPV raster
npv <- (((profit_raster/((1-risk_discount)^1))) + ((profit_raster/((1-risk_discount)^2))) + ((profit_raster/((1-risk_discount)^3))) + ((profit_raster/((1-risk_discount)^4))) + ((profit_raster/((1-risk_discount)^5))) + ((profit_raster/((1-risk_discount)^6))) + ((profit_raster/((1-risk_discount)^7))) + ((profit_raster/((1-risk_discount)^8))) + ((profit_raster/((1-risk_discount)^9))) + ((profit_raster/((1-risk_discount)^10))))/1000000 # divided by 1000000 to convert from USD to billion USD

 # Dataframe NPV
npv_df <- na.omit(as.data.frame(npv))
# Return df
return(npv_df)

}

```

```{r}


# Create sequence of prices for feed
price_feed_seq <- seq(from=2, to=3, by=0.1)

something = sapply(price_feed_seq, function(K) {profits = mapply(FUN=fun_feed_price, feed_price_value=K); return(profits)})

apply_feed_price_df <- t(as.data.frame(do.call(rbind, something)))

colnames(apply_feed_price_df)=price_feed_seq

something2 <- as.data.frame(apply_feed_price_df) %>% 
  gather(feed_price, sum_npv)

feed_price_boxplot <- ggplot(something2, aes(x = feed_price, y = sum_npv, fill=feed_price))+
  geom_boxplot() +
  labs(y="Profits", x = "Feed Price") +
  theme_bw()

feed_price_boxplot

```




